### ISSUE TITLE
This protected script has expired

### ISSUE THREAD

**Issue by lgrunwald** [scnr/installer#11]
The package and the installer stopped working with:

RGLoaderError: RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09]

**Comment by od1tspyd3r** [comment]
I am getting the same error, would love to give this a spin.

**Comment by ShiZiLaiXi** [comment]
I had the same error

**Comment by CollabDSO** [comment]
I am also getting the same error. When will this issue be resolved @Zapotek ?

**Comment by diyarit** [comment]
Same error

**Comment by blackatze93** [comment]
Same here, can't install

**Comment by ShahidAkhterSec** [comment]
It's not fixed , i am still getting this error.
─[~/scnr-1.0dev-1.0dev-1.0dev/bin]
└──╼ $ ./scnr https://plastk.ca
Traceback (most recent call last):
	5: from /home/user/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/gems/bin/scnr:25:in `<main>'
	4: from /home/user/scnr-1.0dev-1.0dev-1.0dev/bin/../.system/gems/bin/scnr:25:in `load'
	3: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/bin/scnr:10:in `<top (required)>'
	2: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/bin/scnr:10:in `require_relative'
	1: from /home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/lib/scnr/ui/cli.rb:2:in `<top (required)>'
/home/user/scnr-1.0dev-1.0dev-1.0dev/.system/gems/gems/scnr-ui-cli-1.0dev/lib/scnr/ui/cli.rb:2:in `RGLoader_load': RubyEncoder Loader - This protected script has expired. Please contact the author of the script about this problem. Error code [09] (RGLoaderError)

**Comment by Threatintel-be** [comment]
same here
