### ISSUE TITLE
Could not initialize Selenium

### ISSUE THREAD

**Issue by j4vaovo** [scnr/installer#23]
````

/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_exception:16] [SCNR::Engine::Browser::Engines::Error] Could not initialize Selenium.
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
 [-] [/root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `init



````

**Comment by Mettthew** [comment]
I have the same problem too, I opened a topic hoping someone would know the solution.

**Comment by Zapotek** [comment]
Hello,

There's an issue when running from root.
Can you please try installing under a regular user account?

I'll add a check for this soon.

Cheers,
Tasos L.

**Comment by MoaathOudeh** [comment]
i have the same issue even when running as non root user

**Comment by reevesy1** [comment]
Same. Is there solution or have you all just looked for something else??

**Comment by Zapotek** [comment]
Hello @moiseslodeiroedosoft ,

The issue has been fixed, at least I can no longer reproduce it.
If you first run it from a root account and then tried a regular user, that might be it, Chrome doesn't work properly afterwards.
Could that be it?

Cheers
