### ISSUE TITLE
Scan immediately terminated with exception

### ISSUE THREAD

**Issue by neverchained** [scnr/installer#26]
Tried on a fresh install of Ubuntu 22.04 LTS and 23.04 with postgresql. Tried both root and default ubuntu user. Scan started via web interface and aborted immediately with the following error:

```
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 2.7.7-p221) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 5956
* Listening on http://0.0.0.0:9292
Use Ctrl-C to stop
I, [2023-10-10T06:23:38.309995 #6008]  INFO -- System: [PID 6008] RPC Server started.
I, [2023-10-10T06:23:38.310033 #6008]  INFO -- System: Listening on 127.0.0.1:39522
I, [2023-10-10T06:23:38.862826 #6008]  INFO -- Call: instance.alive? [127.0.0.1]
I, [2023-10-10T06:23:39.047868 #6008]  INFO -- Call: instance.run [127.0.0.1]
#<Thread:0x0000000003e40b80 /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        14: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        13: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        12: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        11: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
        10: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
         9: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         8: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         7: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         6: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
         5: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
         4: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
         3: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
         2: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
         1: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
/root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
[scnr/engine/ui/output_interface/implemented.rb#print_exception:16] [SCNR::Engine::Browser::Engines::Error] Could not initialize Selenium.
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
[scnr/engine/utilities.rb#exception_jail:400]
[scnr/engine/utilities.rb#exception_jail:401] Parent:
[scnr/engine/utilities.rb#exception_jail:402] SCNR::Engine::Framework
[scnr/engine/utilities.rb#exception_jail:403]
[scnr/engine/utilities.rb#exception_jail:404] Block:
[scnr/engine/utilities.rb#exception_jail:405] #<Proc:0x0000000003e94cf8 /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96>
[scnr/engine/utilities.rb#exception_jail:406]
[scnr/engine/utilities.rb#exception_jail:407] Caller:
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb:395:in `exception_jail'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96:in `run'
[scnr/engine/utilities.rb#exception_jail:408] (eval):39:in `block (2 levels) in <encoded>'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:245:in `block (3 levels) in define_call_router'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:123:in `calling'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:266:in `method_missing'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:244:in `block (2 levels) in define_call_router'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-application-1.0dev/lib/scnr/application.rb:91:in `run'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/cuboid-0.2.7/lib/cuboid/application.rb:40:in `run'
[scnr/engine/utilities.rb#exception_jail:408] /root/scnr/scnr-1.0dev/.system/gems/gems/cuboid-0.2.7/lib/cuboid/rpc/server/application_wrapper.rb:60:in `block in run'
[scnr/engine/utilities.rb#exception_jail:409] --------------------------------------------------------------------------------
#<Thread:0x0000000003e40a68 /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        14: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        13: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        12: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        11: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
        10: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
         9: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         8: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         7: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         6: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
         5: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
         4: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
         3: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
         2: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
         1: from /root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
/root/scnr/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
I, [2023-10-10T06:23:44.126754 #6008]  INFO -- Call: scan.progress [127.0.0.1]
I, [2023-10-10T06:23:44.130152 #6008]  INFO -- Call: instance.generate_report [127.0.0.1]
I, [2023-10-10T06:23:44.173048 #6008]  INFO -- Call: instance.consumed_pids [127.0.0.1]
I, [2023-10-10T06:23:44.176096 #6008]  INFO -- Call: instance.shutdown [127.0.0.1]
I, [2023-10-10T06:23:44.176216 #6008]  INFO -- System: Shutting down in 2 seconds...
```

**Comment by Scourgedoctor** [comment]
I have the same issue. "Could not initialize Selenium" in webdrivers.rb and the scan terminates.

**Comment by Zapotek** [comment]
Hello,

It's the root account.
I'm working on the packages to add a check for that.

Cheers

**Comment by neverchained** [comment]
As I already wrote:

_Tried both root and default ubuntu user_

The Problem occurs with all users.

**Comment by Zapotek** [comment]
Hello,

Did you first try with root by any chance?
After that, permissions for some sort of temp Chrome files prohibit the browser from initializing, even from a normal user.

Cheers

**Comment by neverchained** [comment]
Hey,

give me 2 minutes, i will spin up some machines for testing and reply ASAP.

**Comment by neverchained** [comment]
Ran the install script + the db initialization with the regular ubuntu user and the error persists:

```
ubuntu@scnr01:~/scnr-1.0dev-20230830_190343/scnr-1.0dev$ ./bin/scnr_pro
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 2.7.7-p221) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 6642
* Listening on http://0.0.0.0:9292
Use Ctrl-C to stop
I, [2023-10-22T23:31:19.151071 #6752]  INFO -- System: [PID 6752] RPC Server started.
I, [2023-10-22T23:31:19.151146 #6752]  INFO -- System: Listening on 127.0.0.1:29083
I, [2023-10-22T23:31:19.419166 #6752]  INFO -- Call: instance.alive? [127.0.0.1]
I, [2023-10-22T23:31:19.604141 #6752]  INFO -- Call: instance.run [127.0.0.1]
I, [2023-10-22T23:31:24.656381 #6752]  INFO -- Call: scan.progress [127.0.0.1]
#<Thread:0x00000000016576c8 /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        17: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        16: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        15: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        14: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
        13: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
        12: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
        11: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `initialize'
        10: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
         9: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         8: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         7: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         6: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
         5: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
         4: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
         3: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
         2: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
         1: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
/home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
#<Thread:0x000000000167a1f0 /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:493 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        17: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
        16: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
        15: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
        14: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
        13: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
        12: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
        11: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `initialize'
        10: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
         9: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
         8: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
         7: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
         6: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
         5: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
         4: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
         3: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
         2: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
         1: from /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
/home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception': Could not initialize Selenium. (SCNR::Engine::Browser::Engines::Error)
[scnr/engine/ui/output_interface/implemented.rb#print_exception:16] [SCNR::Engine::Browser::Engines::Error] Could not initialize Selenium.
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `exception'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `fail'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:64:in `selenium'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:33:in `watir'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base/parts/webdriver.rb:94:in `start_webdriver'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:124:in `start'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/engines/base.rb:85:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `new'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/engine.rb:36:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/http.rb:38:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/navigation.rb:39:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser/parts/snapshots.rb:40:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser.rb:62:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/support/mixins/spec_instances.rb:64:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool/worker.rb:56:in `initialize'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `new'
[scnr/engine/ui/output_interface/implemented.rb#print_error_backtrace:12] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/browser_pool.rb:494:in `block (2 levels) in initialize_workers'
[scnr/engine/utilities.rb#exception_jail:400]
[scnr/engine/utilities.rb#exception_jail:401] Parent:
[scnr/engine/utilities.rb#exception_jail:402] SCNR::Engine::Framework
[scnr/engine/utilities.rb#exception_jail:403]
[scnr/engine/utilities.rb#exception_jail:404] Block:
[scnr/engine/utilities.rb#exception_jail:405] #<Proc:0x0000000002d48760 /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96>
[scnr/engine/utilities.rb#exception_jail:406]
[scnr/engine/utilities.rb#exception_jail:407] Caller:
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/utilities.rb:395:in `exception_jail'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-engine-1.0dev/lib/scnr/engine/framework.rb:96:in `run'
[scnr/engine/utilities.rb#exception_jail:408] (eval):39:in `block (2 levels) in <encoded>'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:245:in `block (3 levels) in define_call_router'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:123:in `calling'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:266:in `method_missing'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/dsel-0.1.0/lib/dsel/api/generator.rb:244:in `block (2 levels) in define_call_router'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/scnr-application-1.0dev/lib/scnr/application.rb:91:in `run'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/cuboid-0.2.7/lib/cuboid/application.rb:40:in `run'
[scnr/engine/utilities.rb#exception_jail:408] /home/ubuntu/scnr-1.0dev-20230830_190343/scnr-1.0dev/.system/gems/gems/cuboid-0.2.7/lib/cuboid/rpc/server/application_wrapper.rb:60:in `block in run'
[scnr/engine/utilities.rb#exception_jail:409] --------------------------------------------------------------------------------
I, [2023-10-22T23:31:29.680816 #6752]  INFO -- Call: scan.progress [127.0.0.1]
I, [2023-10-22T23:31:29.682544 #6752]  INFO -- Call: instance.generate_report [127.0.0.1]
I, [2023-10-22T23:31:29.771060 #6752]  INFO -- Call: instance.consumed_pids [127.0.0.1]
I, [2023-10-22T23:31:29.771639 #6752]  INFO -- Call: instance.shutdown [127.0.0.1]
I, [2023-10-22T23:31:29.771869 #6752]  INFO -- System: Shutting down in 2 seconds...
```

**Comment by Zapotek** [comment]
Should be fixed now.

Thanks for the feedback.

**Comment by Zapotek** [comment]
Does this issues still persist on a fresh installation of Ubuntu and SCNR?

**Comment by neverchained** [comment]
I'm happy to report, that the problem no longer exist on a fresh Ubuntu Jammy installation. I could successfully perform a scan. Thank you!
