### ISSUE TITLE
can't access summary

### ISSUE THREAD

**Issue by Bzyczek7** [scnr/installer#33]
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.

**Comment by Zapotek** [comment]
Hello,

Can you please provide some steps to reproduce?

Cheers!

**Comment by Bzyczek7** [comment]
I click on a scan i'm running ... than i click on summary and than i get that error ...

**Comment by Zapotek** [comment]
I can see the issue.

I'll look into it shortly, thanks for the feedback.

**Comment by Bzyczek7** [comment]
![image](https://github.com/scnr/installer/assets/157357274/e26b018f-d4bd-482c-b1c0-69a0dbf84f3c)

**Comment by Bzyczek7** [comment]
my pleasure, running on Ubuntu just FYI

**Comment by Zapotek** [comment]
Any chance you can send me the target in private?

**Comment by Zapotek** [comment]
I meant the domain of the webapp you're scanning.

**Comment by Bzyczek7** [comment]
aaaaaa zdzikiejwarmii.pl

**Comment by Bzyczek7** [comment]
just FYI the summary does not work on any site i'm scanning that belongs to the company i'm working for.

**Comment by Bzyczek7** [comment]
I also see this 

"[ActiveRecord::StatementInvalid] SQLite3::BusyException: database is locked"
[
    [ 0] "/home/marek/scnr-v1.1/.system/gems/gems/sqlite3-1.7.0/lib/sqlite3/statement.rb:108:in `step'",
    [ 1] "/home/marek/scnr-v1.1/.system/gems/gems/sqlite3-1.7.0/lib/sqlite3/statement.rb:108:in `block in each'",
    [ 2] "/home/marek/scnr-v1.1/.system/gems/gems/sqlite3-1.7.0/lib/sqlite3/statement.rb:107:in `loop'",
    [ 3] "/home/marek/scnr-v1.1/.system/gems/gems/sqlite3-1.7.0/lib/sqlite3/statement.rb:107:in `each'",
    [ 4] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:56:in `to_a'",
    [ 5] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:56:in `block (2 levels) in exec_query'",
    [ 6] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'",
    [ 7] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'",
    [ 8] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:47:in `block in exec_query'",
    [ 9] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
    [10] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
    [11] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
    [12] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
    [13] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'",
    [14] "/home/marek/scnr-v1.1/.system/gems/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
    [15] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'",
    [16] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:46:in `exec_query'",
    [17] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'",
    [18] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'",
    [19] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'",
    [20] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:91:in `select_rows'",
    [21] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/relation/finder_methods.rb:344:in `block in exists?'",
    [22] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'",
    [23] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/relation/finder_methods.rb:344:in `exists?'",
    [24] "/home/marek/scnr-v1.1/.system/gems/gems/activerecord-7.0.2.3/lib/active_record/relation.rb:273:in `empty?'",
    [25] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler/helpers/scan.rb:114:in `each_due_scan'",
    [26] "/home/marek/scnr-v1.1/.system/scnr-ui-pro/lib/scan_scheduler.rb:56:in `block in start'",
    [27] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/base.rb:51:in `call_task'",
    [28] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/persistent.rb:23:in `call'",
    [29] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks/periodic.rb:42:in `call'",
    [30] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `block in call'",
    [31] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `each'",
    [32] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr/tasks.rb:95:in `call'",
    [33] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:305:in `block in run'",
    [34] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `loop'",
    [35] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:303:in `run'",
    [36] "/home/marek/scnr-v1.1/.system/gems/gems/raktr-0.0.3/lib/raktr.rb:345:in `block in run_in_thread'"

**Comment by Zapotek** [comment]
Yeah for it's better to switch to PostgreSQL for heavier loads: https://github.com/scnr/installer#scnr-webui
SQLite can only get you so far.

https://github.com/scnr/installer#postgresql

**Comment by Bzyczek7** [comment]
I thought i did

**Comment by Bzyczek7** [comment]
marek@marek-HP-Laptop-17-by3xxx:~/scnr-v1.1/bin$ sudo -u postgres psql 
could not change directory to "/home/marek/scnr-v1.1/bin": Permission denied
psql (14.10 (Ubuntu 14.10-0ubuntu0.22.04.1))
Type "help" for help.

**Comment by Bzyczek7** [comment]
these two commands I execute while in postgres?

mv .system/scnr-ui-pro/config/database.yml .system/scnr-ui-pro/config/database.yml.bak
cp .system/scnr-ui-pro/config/database.postgres.yml .system/scnr-ui-pro/config/database.yml

**Comment by Bzyczek7** [comment]
I have to say these instructions are not working for me ... 
especially these two 
marek@marek-HP-Laptop-17-by3xxx:/$ mv .system/scnr-ui-pro/config/database.yml .system/scnr-ui-pro/config/database.yml.bak
mv: cannot stat '.system/scnr-ui-pro/config/database.yml': No such file or directory

**Comment by Bzyczek7** [comment]
you have to forgive me ... i'm not linux savvy

**Comment by Bzyczek7** [comment]
I see now .system is a hidden folder :P

**Comment by Bzyczek7** [comment]
ok ... so now with the new database it looks really good ... I can see the issues ... I couldn't see this screen before 

![image](https://github.com/scnr/installer/assets/157357274/962b31e3-6dec-440d-96ef-99cb56450ab9)

Thank you for your help.

**Comment by Zapotek** [comment]
Great!

Cheers!
